### ISSUE TITLE
Error after entering film name: ('.' is not recognized as an internal or external command, operable program or batch file) 

### ISSUE THREAD

**Issue by og-carefree** [fabiospampinato/watch#6]
The full error is: 

> Command failed: ./node_modules/.bin/magnet --rows 10 "Sneakers"
> '.' is not recognized as an internal or external command,
> operable program or batch file.

This happens in both Powershell and CMD.

![image](https://user-images.githubusercontent.com/29863520/30025918-a6fc63f2-9172-11e7-82ed-c6280da1f9f1.png)

Currently using Node 8.4.0 x64 on Windows 10 Pro.

**Comment by fabiospampinato** [comment]
It should be fixed with the latest version, 1.2.0.

Do you confirm?

**Comment by og-carefree** [comment]
Can confirm it's now working :)
