### ISSUE TITLE
NOT WORKING npm install -g @fabiospampinato/watch 

### ISSUE THREAD

**Issue by ElecTreeFrying** [fabiospampinato/watch#8]
npm install -g @fabiospampinato/watch

![asdaa](https://user-images.githubusercontent.com/19801459/30048883-d9680fa2-924a-11e7-8891-093871831f44.PNG)

what should I do? it says cannot connect to github.

**Comment by fabiospampinato** [comment]
That's weird.

Some guy having a similar problem suggests to run a:
```
git config --global url."https://".insteadOf git://
```

Another says running this fixed it for him:
```
npm cache clean
```

Can you try if they work for you?

**Comment by ElecTreeFrying** [comment]
slr. problem solved yesterday, dont use free wifi
